#!/bin/sh

/usr/local/bin/gmtkEMtrain -iswp1 -of1 GM_stage1/flists/train_features.flist -nf1 62 -fmt1 htk \
        -of2 GM_stage1/flists/train_labels.flist -ni2 1 -fmt2 ascii \
        -strFile GM_stage1/stage1_train.str \
        -inputMasterFile GM_stage1/stage1_train.master \
        -outputTrainableParameters GM_stage1/stage1_learned_params@D.gmp \
        -maxE 1 \
        -random F

