#!/bin/sh

/usr/local/bin/gmtkJT -iswp1 -of1 /private/tmp/tp761482b2_2cf6_4d65_a2c1_152056c15a87.flist -nf1 64 -fmt1 htk \
        -strFile GM_scenario1/scenario1.str \
        -inputMasterFile GM_scenario1/scenario1.master \
        -inputTrainableParameters GM_scenario1/scenario1_learned_params.gmp \
        -pCliquePrintRange 0 \
        -cCliquePrintRange 0 \
        -eCliquePrintRange 0 \
        -cliqueOutputFileName GM_scenario1/scenario1.post \
        -cliqueListFileName GM_scenario1/scenario1.post \
        -verbosity 0 \
        -cliquePrintFormat ascii

