#!/bin/sh

/usr/local/bin/gmtkJT -iswp1 -of1 GM_localisation_static/flists/test_features.flist -nf1 32 -fmt1 htk \
        -strFile GM_localisation_static/localisation_static.str \
        -inputMasterFile GM_localisation_static/localisation_static.master \
        -inputTrainableParameters GM_localisation_static/localisation_static_learned_params.gmp \
        -pCliquePrintRange 0 \
        -cCliquePrintRange 0 \
        -eCliquePrintRange 0 \
        -cliqueOutputFileName GM_localisation_static/localisation_static.post \
        -cliqueListFileName GM_localisation_static/localisation_static.post \
        -verbosity 0 \
        -cliquePrintFormat ascii

