#!/bin/sh

/usr/local/bin/gmtkEMtrain -iswp1 -of1 GM_localisation_static/flists/train_features.flist -nf1 32 -fmt1 htk \
        -of2 GM_localisation_static/flists/train_labels.flist -ni2 1 -fmt2 ascii \
        -strFile GM_localisation_static/localisation_static_train.str \
        -inputMasterFile GM_localisation_static/localisation_static_train.master \
        -outputTrainableParameters GM_localisation_static/localisation_static_learned_params@D.gmp \
        -maxE 1 \
        -random F

