#!/bin/sh

/usr/local/bin/gmtkEMtrain -iswp1 -of1 GM_fa2014/flists/train_features.flist -nf1 62 -fmt1 htk \
        -of2 GM_fa2014/flists/train_labels.flist -ni2 1 -fmt2 ascii \
        -strFile GM_fa2014/fa2014_train.str \
        -inputMasterFile GM_fa2014/fa2014_train.master \
        -outputTrainableParameters GM_fa2014/fa2014_learned_params@D.gmp \
        -maxE 1 \
        -random F

