classdef PositionHypothesis < Hypothesis
    % POSITIONHYPOTHESIS This class represents the localization results
    %   that have been generated by SegmentationKS for one particular sound
    %   source. The hypothesis will be represented by the estimated angular
    %   position and the corresponding circular variance.
    %
    % AUTHORS:
    %   Christopher Schymura (christopher.schymura@rub.de)
    %   Cognitive Signal Processing Group
    %   Ruhr-Universitaet Bochum
    %   Universitaetsstr. 150, 44801 Bochum    
    
    properties (SetAccess = private)
        sourceIdentifier            % Unique identifier of the particular 
                                    % sound source represented by this
                                    % hypothesis.
        sourcePosition              % Angular position of the represented 
                                    % sound source in [deg].
        positionVariance            % Circular variance of the estimated 
                                    % angular position.
    end
    
    methods
        function obj = PositionHypothesis(sourceIdentifier, ...
                sourcePosition, positionVariance)

        end
    end
end
