classdef SegmentationHypothesis < Hypothesis
    % SEGMENTATIONHYPOTHESIS This class represents the results that have
    %   been generated by the "Segmentaion Knowledge Source" for one
    %   particular signal block. As the KS performs joint segmentation and
    %   localization, the probabilistic segmentation maps and the angular
    %   position estimates for each source are handled by this class.
    %
    % AUTHORS:
    %   Christopher Schymura (christopher.schymura@rub.de)
    %   Cognitive Signal Processing Group
    %   Ruhr-Universitaet Bochum
    %   Universitaetsstr. 150, 44801 Bochum    
    
    properties (SetAccess = private)
        nSources                    % Number of separated sound sources.
        blockSize                   % Size of the data block in [s] that 
                                    % this hypothesis represents.
        sourceLocations             % Angular positions of the represented 
                                    % sound sources in [deg].
        locationVariance            % Circular variances for all estimated 
                                    % angular positions.
        softMasks                   % A set of probabilistic masks 
                                    % associated with each sound source.
                                    % These masks can be used to separate
                                    % maps of auditory features in further
                                    % processing steps.
    end
    
    methods
        function obj = SegmentationHypothesis(nSources, blockSize, mvmModel)

        end
    end
end
